initialSpawn:
    enabled: false
    
initialMessage:
    enabled: false
    message:
     - '&lHello %player%'
     - '&aThere\"re %online% player out of %max%.'
     - '%available% more players can join.'