main: jkku.mc.introgo.Go
version: 1.0.1
name: IntroGo
author: JkKU (Jenrikku)
description: Simple welcome plugin (Custom message and spawn).

commands:
    go-adm:
        description: Admin commands for IntroGo.
        aliases: go-op
        permission: go.admin
        usage: "Usage: /go-[adm/op] [setspawn|info|reload]"
        
permissions:
    go.admin:
        description: Allows to admin IntroGo plugin.
        default: op