main: jkku.introgo.Go
version: 1.0
name: IntroGo
author: Jenrikku (JkKU)
description: A simply plugin that allows the user to create custom messages an also custom teleports.
load: STARTUP

commands:
    ig-admin:
        description: Admin commands for IntroGo.
        aliases: [ig-adm, ig-op]
        permission: ig.admin
        permission-message: Uh?
    m:
        description: Read messages.
    tpt:
        description: Use teleports.
        
permissions:
    ig.admin:
        description: Allows to admin IntroGo plugin.
        default: op