main: jkku.introgo.Go
version: 0.1
name: IntroGo
author: Jenrikku (JkKU)
description: A simply plugin that allows the user to create custom messages an also custom teleports.
load: STARTUP

commands:
    ig-admin:
        description: Admin commands for IntroGo.
        aliases: [ig-adm, ig-op]
        permission: ig.admin
        permission-message: Uh?
    m:
        description: Read messages.
    tp:
        description: Use teleports.
        
permissions:
    ig.admin:
        description: Allows to admin IntroGo plugin.
        default: op